name: Run tests

on:
  push:
    branches:
      - main

jobs:
  clean_space:
    name: show df
    runs-on: ubuntu-24.04
    steps:
      - name: Clean Disk
        run: | 
          du -sh /usr/lib/jvm
          sudo rm -rf /usr/lib/jvm
          du -sh /usr/share/dotnet
          sudo rm -rf /usr/share/dotnet
          du -sh /usr/share/swift
          sudo rm -rf /usr/share/swift
          du -sh /usr/local/.ghcup
          sudo rm -rf /usr/local/.ghcup
          du -sh /home/runner/.rustup
          sudo rm -rf /home/runner/.rustup
          du -sh /usr/local/julia*
          sudo rm -rf /usr/local/julia*
      - name: Clean SDK 
        run: | 
          sudo ls /usr/local/lib/
          sudo ls opt/
          du -sh /usr/local/lib/android/sdk
          sudo rm -rf /usr/local/lib/android/sdk
          du -sh /usr/local/share/chromium
          sudo rm -rf /usr/local/share/chromium
          du -sh /opt/az
          sudo rm -rf /opt/az
          du -sh /usr/local/share/powershell
          sudo rm -rf /usr/local/share/powershell
          du -sh /opt/hostedtoolcache
          sudo rm -rf /opt/hostedtoolcache
          du -sh /opt/google
          sudo rm -rf /opt/google
          
      - name: Show disk usage
        run: |
          df -h
