name: Run tests

on:
  push:
    branches:
      - main

jobs:
  clean_space:
    name: show df
    runs-on: ubuntu-24.04
    steps:
      - name: Show disk usage
        run: |
          df -h
      - name: Clean Disk
        uses: SerhiiK/gha-cleaner@v1.0
        with:
          remove-all: "true"
      - name: Show disk usage
        run: |
          df -h
